doctrine/collections

- lib/Doctrine/Common/Collections/AbstractLazyCollection.php
I'm working on making PersistentCollection extends AbstractLazyCollection and it is required to have access to initialized property. This PR allows that.
> Made initialized protected for extensibility.

- lib/Doctrine/Common/Collections/Criteria.php
Just a suggestion - will add tests for it later if this is actually wanted behavior
Ping @EvanDotPro
> Explicit casting of first and max results

- lib/Doctrine/Common/Collections/ArrayCollection.php
Use `uksort()` instead of `usort()`.
> Keep keys when using array collection's matching()

- .travis.yml
hhvm-nightly is not available anymore on Travis for now, because HHVM dropped support for Ubuntu 10.04
> Remove the hhvm-nightly job from the matrix

- lib/Doctrine/Common/Collections/ArrayCollection.php
- tests/Doctrine/Tests/Common/Collections/ArrayCollectionTest.php
This is a copy of #59 that includes unit tests.
> Arraycollection matching method multiple ordering fix

- .gitignore
This PR
:information_desk_person: It's apparently not checked in, so it should be ignored, right?
> Fix: Ignore composer.lock

- tests/Doctrine/Tests/Common/Collections/CriteriaTest.php
> Fix: Assert expression is set when none has before

- lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
- lib/Doctrine/Common/Collections/Expr/Comparison.php
- lib/Doctrine/Common/Collections/ExpressionBuilder.php
- tests/Doctrine/Tests/Common/Collections/ClosureExpressionVisitorTest.php
- tests/Doctrine/Tests/Common/Collections/ExpressionBuilderTest.php
Hi,
The comparison MEMBER_OF was not implemented on Cretieria while it seems really easy to implement.
I implemented it and wrote the test.
I also tested it in my application.
> implement ExpressionBuilder->memberOf() method

- lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
- tests/Doctrine/Tests/Common/Collections/ClosureExpressionVisitorTest.php
Because people keep running into issues with collections and `$underscore_properties` , I have added extra tests on the changes of #29 to to prove that it's backwards compatible. It seems like that one won't be merged because the test cases are missing.
This PR includes the exact same changes as #29 but with 3 extra tests.
> non-camel-case variable code conventions (with extra tests)

- lib/Doctrine/Common/Collections/ExpressionBuilder.php
comparision should be comparison in the class docBlock.
> Spelling - comparision should be comparison

- tests/Doctrine/Tests/Common/Collections/Expr/CompositeExpressionTest.php
- tests/Doctrine/Tests/Common/Collections/Expr/ValueTest.php
I added two unit tests. One for ValueExpression and the other for CompositeExpression.
The @covers annotation defines clearly which class I want to test (Subject under test)
I hope that this will fit to the standards :)
Cheers Tobias
> Add unit tests for value and composite expression

- composer.json
Ref: https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md
@Ocramius I heard you hate unbound version constraint on PHP... :stuck_out_tongue:
> Do not target unbound PHP version contraint

- CONTRIBUTING.md
- composer.json
[resolves #102 ] Doctrine ORM [CONTRIBUTING.md](https://github.com/doctrine/doctrine2/blob/master/CONTRIBUTING.md) changed to collections context.
> Contributing guide

- lib/Doctrine/Common/Collections/ArrayCollection.php
This goes hand in hand with https://github.com/doctrine/collections/pull/91
If you add new method in your derived class, IDE without this patch doesn't know it's there after you call some fluent method.
> Fix DocBlock for derived classes

- .travis.yml
- lib/Doctrine/Common/Collections/ArrayCollection.php
- lib/Doctrine/Common/Collections/Criteria.php
- lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
- lib/Doctrine/Common/Collections/Expr/Comparison.php
- lib/Doctrine/Common/Collections/Expr/CompositeExpression.php
- tests/Doctrine/Tests/Common/Collections/AbstractLazyArrayCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/AbstractLazyCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/ArrayCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/BaseArrayCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/BaseCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/ClosureExpressionVisitorTest.php
- tests/Doctrine/Tests/Common/Collections/CollectionTest.php
- tests/Doctrine/Tests/Common/Collections/CriteriaTest.php
- tests/Doctrine/Tests/Common/Collections/DerivedCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/Expr/CompositeExpressionTest.php
- tests/Doctrine/Tests/Common/Collections/Expr/ValueTest.php
- tests/Doctrine/Tests/Common/Collections/ExpressionBuilderTest.php
- tests/Doctrine/Tests/DerivedArrayCollection.php
- tests/Doctrine/Tests/LazyArrayCollection.php
Related to https://github.com/doctrine/doctrine2/issues/6425
> Require PHP 7.1

- composer.json
7.1 is required since #119, but composer was not updated.
> Add missing PHP version bumping to 7.1

- lib/Doctrine/Common/Collections/Collection.php
I updated the return typehint of docblock partition function. This way I believe it is easier what to expect and offers auto completion for the IDE.
> Updated the return typehint docblock of partition

- lib/Doctrine/Common/Collections/AbstractLazyCollection.php
- lib/Doctrine/Common/Collections/Collection.php
What the title says.
But also I need to make a question here. Since you bumbed to php7.1 why you haven't used return types for the functions?
> Converted the docblocks of ArrayCollection to short type hints

- CONTRIBUTING.md
- composer.json
- lib/Doctrine/Common/Collections/AbstractLazyCollection.php
- lib/Doctrine/Common/Collections/ArrayCollection.php
- lib/Doctrine/Common/Collections/Collection.php
- lib/Doctrine/Common/Collections/Criteria.php
- lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
- lib/Doctrine/Common/Collections/Expr/Comparison.php
- lib/Doctrine/Common/Collections/Expr/CompositeExpression.php
- lib/Doctrine/Common/Collections/Expr/Expression.php
- lib/Doctrine/Common/Collections/Expr/ExpressionVisitor.php
- lib/Doctrine/Common/Collections/ExpressionBuilder.php
- lib/Doctrine/Common/Collections/Selectable.php
- phpcs.xml.dist
- tests/Doctrine/Tests/Common/Collections/AbstractLazyArrayCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/AbstractLazyCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/BaseArrayCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/BaseCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/ClosureExpressionVisitorTest.php
- tests/Doctrine/Tests/Common/Collections/CollectionTest.php
- tests/Doctrine/Tests/Common/Collections/CriteriaTest.php
- tests/Doctrine/Tests/Common/Collections/DerivedCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/Expr/CompositeExpressionTest.php
- tests/Doctrine/Tests/Common/Collections/Expr/ValueTest.php
- tests/Doctrine/Tests/Common/Collections/ExpressionBuilderTest.php
- tests/Doctrine/Tests/DerivedArrayCollection.php
BC-breaking sniffs disabled. Also disabled checks for iterable types since Collections are built around mixed values.
> Apply Doctrine CS 2.1

- docs/en/index.rst
This PR covers the issues #156 and doctrine/doctrine-website#191.
I've separated `Selectable::matching()` from the `Collection` interface part and put it into its own section. I also fixed the link to the expressions page.
> Extract Selectable method into own documentation section

- lib/Doctrine/Common/Collections/ArrayCollection.php
- tests/Doctrine/Tests/Common/Collections/BaseCollectionTest.php
Uses ARRAY_FILTER_USE_BOTH in the underlying array_filter function. Does
not cause BC Break.
Any examples where how to run benchmarks against this?
https://github.com/doctrine/collections/issues/165
> Allow `ArrayCollection#filter()` to filter by key and also value

- docs/en/index.rst
The example referenced an incorrect variable name.
> Fix `forAll` example.

- lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
- tests/Doctrine/Tests/Common/Collections/ClosureExpressionVisitorTest.php
This PR tries to fix an issue I am facing in my application that uses Doctrine2 ORM.
I have the following setup:
```php
class Platform {
// ..
/**
* @ORM\OneToMany(targetEntity="PaymentMethod", mappedBy="platform")
*/
private $paymentMethods;
}
class PaymentMethod {
// ...
/**
* @ORM\Column(type="boolean")
*/
private $isActive = true;
}
```
I'm trying to get all PaymentMethods from the Platform that are active:
```php
class Platform {
// ..
public function getActivePaymentMethods() : Collection
{
$criteria = Criteria::create()
->where(Criteria::expr()->eq('isActive', true));
return $this->paymentMethods->matching($criteria);
}
}
```
When I call `$platform->getActivePaymentMethods()` I get:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Cannot access private property …
```
> ClosureExpressionVisitor > Don't duplicate the accessor when the field already starts with it

- composer.json
- composer.lock
- lib/Doctrine/Common/Collections/AbstractLazyCollection.php
- lib/Doctrine/Common/Collections/ArrayCollection.php
- lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
- lib/Doctrine/Common/Collections/Expr/ExpressionVisitor.php
Updated coding-standard and used `phpcbf` to automatically fix them
> Updated doctrine/coding-standard to 6.0

- .scrutinizer.yml
- .travis.yml
- composer.json
- composer.lock
- lib/Doctrine/Common/Collections/AbstractLazyCollection.php
- lib/Doctrine/Common/Collections/ArrayCollection.php
- lib/Doctrine/Common/Collections/Collection.php
- lib/Doctrine/Common/Collections/Criteria.php
- lib/Doctrine/Common/Collections/Selectable.php
- psalm.xml.dist
I've talked to @Ocramius and we find that generics/template types would make a very good addition to this library. Since PHP doesn't come with that feature natively, I have decided to implement it using Psalm and [Psalm's template annotations](https://psalm.dev/docs/templated_annotations/).  
**How is that useful?**
A lot of people already use static analysis to reduce the risk of introducing bugs in your application. Psalm is one of the most popular tools out there to do that. By adding the annotations to Psalm and using the correct `@psalm-var` annotations when using the collections in projects, Psalm makes sure that you only put values of the right type in your collection automatically, since it also scans the `vendor` directory.  
I have created a very minimal proof of concept project …
> Generify collections using Psalm

- lib/Doctrine/Common/Collections/Collection.php
Since the key was added to the closure of `ArrayCollection::filter` in 1.6.0 I guess this needs to be updated.
> Update Collection::filter docblock to add key parameter to closure

- lib/Doctrine/Common/Collections/AbstractLazyCollection.php
- lib/Doctrine/Common/Collections/ArrayCollection.php
- lib/Doctrine/Common/Collections/Collection.php
- lib/Doctrine/Common/Collections/Selectable.php
Following reports that some users encountered issues with `@template` annotations, this PR replaces `@template` with the functionally-equivalent `@psalm-template`.
> Use @psalm-template annotation to avoid clashes

- docs/en/serialization.rst
- docs/en/sidebar.rst
Hints about the serialization of collections can be found in the collection code comments, but they are missing in the documentation. This PR contains a minimal documentation about the serialization.
Do we need more examples or a section for third-party serialization libraries?
> Documentation for serialization of collections

- docs/en/index.rst
- lib/Doctrine/Common/Collections/ArrayCollection.php
- lib/Doctrine/Common/Collections/Selectable.php
- tests/Doctrine/Tests/Common/Collections/BaseArrayCollectionTest.php
- tests/Doctrine/Tests/Common/Collections/CollectionTest.php
When a `Crieria` is used with a set firstresult or maxresult, the keys of the resulting ArrayCollection are not preserved.
Because keys are kept on `map` or `filter` too, I expect `matching`, like with the order criteria, to keep the keys with a criteria that slices a result.
> Preserve keys in ArrayCollection for Criteria firstresults/maxresults

- composer.json
- composer.lock
- lib/Doctrine/Common/Collections/ArrayCollection.php
- tests/Doctrine/Tests/Common/Collections/ArrayCollectionTest.php
Initialize the property $element to an Array in order to avoid warning when we unserialize a serialized array (see #155) :
`Warning: array_values() expects parameter 1 to be array, null given`
> Initialize $element property of ArrayCollection

- lib/Doctrine/Common/Collections/ArrayCollection.php
Apparently, psalm cannot reuse `@psalm-template` from parent's method declaration using `@inheritdoc`, so we cannot just specify `@psalm-return static<TKey, U>`.
Fixes #210
> fix #210 by including psalm-* annotations to ArrayCollection#map()

- lib/Doctrine/Common/Collections/ExpressionBuilder.php
Like https://github.com/doctrine/collections/pull/217 but changes only PHPDoc
> reflect that ExpressionBuilder#andX() and orX() params are variadic in PHPDoc

- .doctrine-project.json
This should fix the collections version infos and the build error `error: pathspec 'origin/1.6' did not match any file(s) known to git` on Doctrine website build.
> Fix of branch name for doctrine website build

- composer.json
This was useful when master was 1.6, but currently it is 2.0, so this
will only cause confusion. When releasing 2.0.0, we should create a
similar commit on the newly created 2.0.x branch, and bump that number
in the master branch.
> Remove stale branch alias

- composer.json
- composer.lock
- lib/Doctrine/Common/Collections/AbstractLazyCollection.php
- lib/Doctrine/Common/Collections/ArrayCollection.php
- lib/Doctrine/Common/Collections/Collection.php
- lib/Doctrine/Common/Collections/Selectable.php
This should also help PHPStan understand the collections class a little better, as it doesn't support `array-key` yet.
> Update Psalm and fix a few issues
